// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://htkhwppmvmihnfiytscz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh0a2h3cHBtdm1paG5maXl0c2N6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5OTQyMDIsImV4cCI6MjA2NzU3MDIwMn0.Cx9Ko-XFPdmPsyAZFnjy0-7YYFe3po1pS1mlHVwB8VU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});